### ISSUE TITLE
No active distribution profiles found / List not showing all profiles

### ISSUE THREAD

**Issue by Cedrick84** [nomad/cupertino#209] opened 2015-04-23 07:30 UTC
Using the latest version of cupertino I can't seem to download some distribution profiles, when I specify them by name (which is correct) I get the error "No active distribution profiles found".

When I try to list my profiles by doing:
```
ios profiles:list --team [teamid] --type distribution
```

It only lists me the first x number of profiles, it seems as if only the "first page" is loaded. The profiles I'm looking for would be on page number three. My guess is this is why it doesn't find my profile when I'm looking for it by name. The profiles on the first page are expired, thats why the "no active profiles" error makes sense if it thinks those are the only ones I have.

Thanks for looking into this.

**Comment by sfransen** [comment] 2015-04-23 12:44
Change the page number in agent.rb to larger number then 50

**Comment by Cedrick84** [comment] 2015-04-23 12:53
@sfransen thank you for this tip, this indeed downloads the profile correctly. Although I think a fix should be made for this, especially when querying a profile by name it should just get it, and when the list is shown you should be able to get to the next page.

Thanks again for helping me "solve" this issue.

**Comment by sfransen** [comment] 2015-04-23 13:20
The problem is  you have more 50 items and apple change the web and we have to pass page number now if number is not big enough it fails the for each or even to list them

**Comment by mattt** [comment] 2015-05-19 13:03
Fixed by #216.

**Closed by mattt** 2015-05-19 13:03 UTC
