### ISSUE TITLE
Odd formatting issue?

### ISSUE THREAD

**Issue by danieljimenez** [nomad/cupertino#199] opened 2015-04-13 12:09 UTC
Since the latest release (1.3.2, downloaded this morning)... there are some odd formatting issues with Cupertino's output.

![2015-04-13 at 7 08 am](https://cloud.githubusercontent.com/assets/63831/7115218/0561f7dc-e1ac-11e4-9b00-6724bf36a672.jpg)

**Comment by mattt** [comment] 2015-04-13 13:20
Duplicate of #246.

**Closed by mattt** 2015-04-13 13:20 UTC

**Comment by mattt** [comment] 2015-04-13 13:43
Fixed for 1.3.3.

**Comment by danieljimenez** [comment] 2015-04-13 13:47
Still seeing this in 1.3.3 :(

**Comment by danieljimenez** [comment] 2015-04-13 13:48
![2015-04-13 at 8 48 am](https://cloud.githubusercontent.com/assets/63831/7116794/e99d1442-e1b9-11e4-8c49-68d1c1c99d54.jpg)
